### ISSUE TITLE
Отсутствует метод расширения Authorize()

### ISSUE THREAD

**Issue by imbananko** [virtyaluk/InTouch#25]
В последней сборке отсутствует метод расширения Authorize(). Просьба изменить раздел "Usage"

**Comment by greymem** [comment]
Если это поможет, то я получаю готовый ключ, а затем использую
```
InTouch.SetSessionData(userToken, userId, 0);
InTouch.SetServiceToken("<Сервисный ключ доступа полученный из настроек приложения https://vk.com/editapp?id=<ID приложения>&section=options>");
```
Для простых методов работает, все еще не проверял

**Comment by virtyaluk** [comment]
@imbananko, 
> Authorization works only in Windows (and WinPhone) Store Apps
> otherwise you'll need to set received "access_token" manually
> using SetSessionData method.

У Вас точно `Windows (and WinPhone) Store Apps`?

**Comment by asimaranov** [comment]
Столкнулся с такой же проблемой
