### ISSUE TITLE
Ошибка при загрузке фото

### ISSUE THREAD

**Issue by Arthur1PO-14** [virtyaluk/InTouch#27]
При попытке загрузки фотографий на сервер (с использованием любого метода Upload раздела Photos) вылетает ошибка. Вот сообщение из InnerException: "Message "Invalid photo: bad format \"file\" file, from upl_639427?act=owner_photo"	string"
Ругается на метод, парсящий JSON

**Comment by virtyaluk** [comment]
@Arthur1PO-14, ошибка еще воспроизводится?
