### ISSUE TITLE
Почему лицензировано под GPL?

### ISSUE THREAD

**Issue by AlexByte** [virtyaluk/InTouch#31]

**Comment by virtyaluk** [comment]
@AlexByte, библиотека лицензирована, как открытое ПО. Лицензия вполне соответствует проекту.

**Comment by AlexByte** [comment]
Чем не устраивает LGPL?

**Comment by virtyaluk** [comment]
@AlexByte, я выбрал лицензию основываясь на том, что выбирали для других открытых проектов. Сейчас вижу, что LGPL имеет преимущество при использовании в коммерческих проектах. Если суть в этом, то имеет смысл заменить лицензию.
