### ISSUE TITLE
Auth by login and pass

### ISSUE THREAD

**Issue by N1cE174** [virtyaluk/InTouch#9]
Можете добавить метод прямой авторизации `client.Auth(login, pass, smscode, captcha)`?
Т.е. авторизация через UI моем в приложении, а не через WebView

**Comment by mokeev1995** [comment]
@N1cE174 если вы хотите, чтобы было как в приложении вк, то так не получится. если нет, то получается, что вы хотите, чтоб в библиотеке само по себе выбрасывалось окошко с webview при авторизации. так?

**Comment by virtyaluk** [comment]
@N1cE174,
@mokeev1995,
сценария с выбрасыванием webview не будет т.к. эти вещи платформозависимые, а здесь уже и так много платформ(`.NET`, `Xamarin`, `Silverlight`, `Windows Store`, `Windows Phone`, `.NET Core`).

Прямая авторизация состоит из нескольких шагов. Один из которых состоит в "переходе по ссылке". По-этому, нет никаких гарантий, что выйдет реализовать прямую авторизацию. Ну, посмотрим.

**Comment by mokeev1995** [comment]
@virtyaluk так о чем и речь, там надо просто делать подмену того, что происходит на странице авторизации вк, оно того стоит?

**Comment by virtyaluk** [comment]
@mokeev1995, думаю нет.
